title: Game Boy Wiki
description: The place for information about Nintendo's Game Boy handhelds, from accesories to modded consoles.
url: https://rgameboy.github.io

timezone: Europe/London

sass:
  sass_dir: assets/css/bulma