title: Game Boy Resource
description: The place for information and tools for Nintendo's Game Boy handhelds.
url: https://gameboy.github.io

timezone: Europe/London

sass:
  sass_dir: assets/css/bulma
